// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSystem.Server.Data;

#nullable disable

namespace SkillSystem.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230521114003_addNumber")]
    partial class addNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillSystem.Shared.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("SkillTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "提高英语能力，通过英语四级",
                            Name = "英语四级培训课",
                            SkillId = 2,
                            SkillTypeId = 4
                        },
                        new
                        {
                            Id = 2,
                            Description = "提高计算机能力，通过计算机四级",
                            Name = "计算机四级培训课",
                            SkillId = 1,
                            SkillTypeId = 4
                        },
                        new
                        {
                            Id = 3,
                            Description = "提高Office能力，通过Office二级",
                            Name = "Office二级培训课",
                            SkillId = 4,
                            SkillTypeId = 2
                        });
                });

            modelBuilder.Entity("SkillSystem.Shared.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "负责人事管理相关工作",
                            Name = "人事管理部"
                        },
                        new
                        {
                            Id = 2,
                            Description = "负责产品开发相关工作",
                            Name = "开发部"
                        },
                        new
                        {
                            Id = 3,
                            Description = "负责人员联络工作",
                            Name = "联络部"
                        });
                });

            modelBuilder.Entity("SkillSystem.Shared.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Job");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "人事管理部主管",
                            Name = "部门主管"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Description = "开发部主管",
                            Name = "部门主管"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Description = "联络部主管",
                            Name = "部门主管"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Description = "人事管理部普通员工",
                            Name = "普通员工"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Description = "人事管理部普通员工",
                            Name = "普通员工"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Description = "开发部普通员工",
                            Name = "普通员工"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 2,
                            Description = "开发部普通员工",
                            Name = "普通员工"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 3,
                            Description = "联络部普通员工",
                            Name = "普通员工"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 3,
                            Description = "联络部普通员工",
                            Name = "普通员工"
                        });
                });

            modelBuilder.Entity("SkillSystem.Shared.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skill");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "计算机操作能力",
                            Name = "计算机"
                        },
                        new
                        {
                            Id = 2,
                            Description = "英语交流能力",
                            Name = "英语"
                        },
                        new
                        {
                            Id = 3,
                            Description = "普通话交流能力",
                            Name = "普通话"
                        },
                        new
                        {
                            Id = 4,
                            Description = "办公软件能力",
                            Name = "Office"
                        });
                });

            modelBuilder.Entity("SkillSystem.Shared.SkillType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "一级"
                        },
                        new
                        {
                            Id = 2,
                            Name = "二级"
                        },
                        new
                        {
                            Id = 3,
                            Name = "三级"
                        },
                        new
                        {
                            Id = 4,
                            Name = "四级"
                        });
                });

            modelBuilder.Entity("SkillSystem.Shared.SkillVariant", b =>
                {
                    b.Property<int>("SkillTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillTypeId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillVariants");

                    b.HasData(
                        new
                        {
                            SkillTypeId = 2,
                            SkillId = 1,
                            Difficulty = "简单"
                        },
                        new
                        {
                            SkillTypeId = 4,
                            SkillId = 2,
                            Difficulty = "中等"
                        },
                        new
                        {
                            SkillTypeId = 2,
                            SkillId = 3,
                            Difficulty = "简单"
                        },
                        new
                        {
                            SkillTypeId = 4,
                            SkillId = 3,
                            Difficulty = "简单"
                        },
                        new
                        {
                            SkillTypeId = 2,
                            SkillId = 4,
                            Difficulty = "简单"
                        },
                        new
                        {
                            SkillTypeId = 4,
                            SkillId = 4,
                            Difficulty = "中等"
                        });
                });

            modelBuilder.Entity("SkillSystem.Shared.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Training");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Description = "第一年度春季英语培训",
                            EndTime = new DateTime(2023, 6, 27, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(848),
                            MaxCapacity = 50,
                            Name = "第一年度春季英语培训",
                            RegisterNumber = 0,
                            StartTime = new DateTime(2023, 5, 28, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(838),
                            Status = "未开始",
                            Type = "线下"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Description = "第一年度秋季计算机培训",
                            EndTime = new DateTime(2023, 11, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(852),
                            MaxCapacity = 10,
                            Name = "第一年度秋季计算机培训",
                            RegisterNumber = 0,
                            StartTime = new DateTime(2023, 8, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(850),
                            Status = "未开始",
                            Type = "线上"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Description = "第一年度夏季Office培训",
                            EndTime = new DateTime(2023, 10, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(854),
                            MaxCapacity = 30,
                            Name = "第一年度夏季Office培训",
                            RegisterNumber = 0,
                            StartTime = new DateTime(2023, 7, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(854),
                            Status = "未开始",
                            Type = "线上"
                        });
                });

            modelBuilder.Entity("SkillSystem.Shared.TrainingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RegisterTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingItems");
                });

            modelBuilder.Entity("SkillSystem.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSuper")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 5, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(1071),
                            Email = "duyou@example.com",
                            JobId = 1,
                            Name = "董磊",
                            PasswordHash = new byte[] { 193, 126, 114, 212, 29, 138, 149, 19, 191, 218, 90, 30, 54, 169, 57, 56, 14, 24, 98, 131, 129, 250, 145, 44, 135, 115, 117, 239, 24, 180, 208, 105, 36, 4, 135, 49, 124, 227, 161, 42, 151, 15, 48, 6, 17, 76, 169, 194, 228, 180, 34, 39, 100, 244, 128, 239, 195, 162, 7, 14, 98, 81, 38, 195 },
                            PasswordSalt = new byte[] { 54, 42, 28, 151, 37, 146, 91, 51, 52, 216, 65, 141, 157, 16, 63, 164, 10, 213, 32, 82, 168, 168, 188, 117, 63, 68, 166, 138, 134, 83, 201, 176, 84, 14, 185, 154, 48, 61, 170, 219, 139, 95, 44, 158, 40, 51, 18, 152, 163, 166, 46, 43, 59, 7, 207, 128, 153, 115, 233, 192, 103, 151, 41, 169, 170, 237, 79, 230, 77, 3, 27, 44, 161, 98, 177, 202, 107, 104, 127, 29, 103, 164, 248, 5, 2, 84, 249, 231, 218, 218, 144, 213, 104, 228, 30, 32, 21, 68, 54, 55, 74, 150, 197, 44, 70, 255, 45, 249, 115, 154, 83, 177, 34, 34, 122, 191, 2, 101, 171, 106, 92, 158, 236, 162, 225, 6, 210, 241 },
                            Phone = "12355556666",
                            Sex = "男",
                            isSuper = false
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 5, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(1073),
                            Email = "duyou2@example.com",
                            JobId = 3,
                            Name = "庄娅",
                            PasswordHash = new byte[] { 193, 126, 114, 212, 29, 138, 149, 19, 191, 218, 90, 30, 54, 169, 57, 56, 14, 24, 98, 131, 129, 250, 145, 44, 135, 115, 117, 239, 24, 180, 208, 105, 36, 4, 135, 49, 124, 227, 161, 42, 151, 15, 48, 6, 17, 76, 169, 194, 228, 180, 34, 39, 100, 244, 128, 239, 195, 162, 7, 14, 98, 81, 38, 195 },
                            PasswordSalt = new byte[] { 54, 42, 28, 151, 37, 146, 91, 51, 52, 216, 65, 141, 157, 16, 63, 164, 10, 213, 32, 82, 168, 168, 188, 117, 63, 68, 166, 138, 134, 83, 201, 176, 84, 14, 185, 154, 48, 61, 170, 219, 139, 95, 44, 158, 40, 51, 18, 152, 163, 166, 46, 43, 59, 7, 207, 128, 153, 115, 233, 192, 103, 151, 41, 169, 170, 237, 79, 230, 77, 3, 27, 44, 161, 98, 177, 202, 107, 104, 127, 29, 103, 164, 248, 5, 2, 84, 249, 231, 218, 218, 144, 213, 104, 228, 30, 32, 21, 68, 54, 55, 74, 150, 197, 44, 70, 255, 45, 249, 115, 154, 83, 177, 34, 34, 122, 191, 2, 101, 171, 106, 92, 158, 236, 162, 225, 6, 210, 241 },
                            Phone = "12355553333",
                            Sex = "女",
                            isSuper = false
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2023, 5, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(1106),
                            Email = "duyou3@example.com",
                            JobId = 2,
                            Name = "罗山",
                            PasswordHash = new byte[] { 193, 126, 114, 212, 29, 138, 149, 19, 191, 218, 90, 30, 54, 169, 57, 56, 14, 24, 98, 131, 129, 250, 145, 44, 135, 115, 117, 239, 24, 180, 208, 105, 36, 4, 135, 49, 124, 227, 161, 42, 151, 15, 48, 6, 17, 76, 169, 194, 228, 180, 34, 39, 100, 244, 128, 239, 195, 162, 7, 14, 98, 81, 38, 195 },
                            PasswordSalt = new byte[] { 54, 42, 28, 151, 37, 146, 91, 51, 52, 216, 65, 141, 157, 16, 63, 164, 10, 213, 32, 82, 168, 168, 188, 117, 63, 68, 166, 138, 134, 83, 201, 176, 84, 14, 185, 154, 48, 61, 170, 219, 139, 95, 44, 158, 40, 51, 18, 152, 163, 166, 46, 43, 59, 7, 207, 128, 153, 115, 233, 192, 103, 151, 41, 169, 170, 237, 79, 230, 77, 3, 27, 44, 161, 98, 177, 202, 107, 104, 127, 29, 103, 164, 248, 5, 2, 84, 249, 231, 218, 218, 144, 213, 104, 228, 30, 32, 21, 68, 54, 55, 74, 150, 197, 44, 70, 255, 45, 249, 115, 154, 83, 177, 34, 34, 122, 191, 2, 101, 171, 106, 92, 158, 236, 162, 225, 6, 210, 241 },
                            Phone = "12355557777",
                            Sex = "男",
                            isSuper = false
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2023, 5, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(1107),
                            Email = "duyou4@example.com",
                            JobId = 4,
                            Name = "薛马俊",
                            PasswordHash = new byte[] { 193, 126, 114, 212, 29, 138, 149, 19, 191, 218, 90, 30, 54, 169, 57, 56, 14, 24, 98, 131, 129, 250, 145, 44, 135, 115, 117, 239, 24, 180, 208, 105, 36, 4, 135, 49, 124, 227, 161, 42, 151, 15, 48, 6, 17, 76, 169, 194, 228, 180, 34, 39, 100, 244, 128, 239, 195, 162, 7, 14, 98, 81, 38, 195 },
                            PasswordSalt = new byte[] { 54, 42, 28, 151, 37, 146, 91, 51, 52, 216, 65, 141, 157, 16, 63, 164, 10, 213, 32, 82, 168, 168, 188, 117, 63, 68, 166, 138, 134, 83, 201, 176, 84, 14, 185, 154, 48, 61, 170, 219, 139, 95, 44, 158, 40, 51, 18, 152, 163, 166, 46, 43, 59, 7, 207, 128, 153, 115, 233, 192, 103, 151, 41, 169, 170, 237, 79, 230, 77, 3, 27, 44, 161, 98, 177, 202, 107, 104, 127, 29, 103, 164, 248, 5, 2, 84, 249, 231, 218, 218, 144, 213, 104, 228, 30, 32, 21, 68, 54, 55, 74, 150, 197, 44, 70, 255, 45, 249, 115, 154, 83, 177, 34, 34, 122, 191, 2, 101, 171, 106, 92, 158, 236, 162, 225, 6, 210, 241 },
                            Phone = "12355554444",
                            Sex = "男",
                            isSuper = false
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2023, 5, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(1109),
                            Email = "duyou5@example.com",
                            JobId = 5,
                            Name = "彭广",
                            PasswordHash = new byte[] { 193, 126, 114, 212, 29, 138, 149, 19, 191, 218, 90, 30, 54, 169, 57, 56, 14, 24, 98, 131, 129, 250, 145, 44, 135, 115, 117, 239, 24, 180, 208, 105, 36, 4, 135, 49, 124, 227, 161, 42, 151, 15, 48, 6, 17, 76, 169, 194, 228, 180, 34, 39, 100, 244, 128, 239, 195, 162, 7, 14, 98, 81, 38, 195 },
                            PasswordSalt = new byte[] { 54, 42, 28, 151, 37, 146, 91, 51, 52, 216, 65, 141, 157, 16, 63, 164, 10, 213, 32, 82, 168, 168, 188, 117, 63, 68, 166, 138, 134, 83, 201, 176, 84, 14, 185, 154, 48, 61, 170, 219, 139, 95, 44, 158, 40, 51, 18, 152, 163, 166, 46, 43, 59, 7, 207, 128, 153, 115, 233, 192, 103, 151, 41, 169, 170, 237, 79, 230, 77, 3, 27, 44, 161, 98, 177, 202, 107, 104, 127, 29, 103, 164, 248, 5, 2, 84, 249, 231, 218, 218, 144, 213, 104, 228, 30, 32, 21, 68, 54, 55, 74, 150, 197, 44, 70, 255, 45, 249, 115, 154, 83, 177, 34, 34, 122, 191, 2, 101, 171, 106, 92, 158, 236, 162, 225, 6, 210, 241 },
                            Phone = "12322226666",
                            Sex = "男",
                            isSuper = false
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2023, 5, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(1110),
                            Email = "duyou6@example.com",
                            JobId = 6,
                            Name = "韦峰",
                            PasswordHash = new byte[] { 193, 126, 114, 212, 29, 138, 149, 19, 191, 218, 90, 30, 54, 169, 57, 56, 14, 24, 98, 131, 129, 250, 145, 44, 135, 115, 117, 239, 24, 180, 208, 105, 36, 4, 135, 49, 124, 227, 161, 42, 151, 15, 48, 6, 17, 76, 169, 194, 228, 180, 34, 39, 100, 244, 128, 239, 195, 162, 7, 14, 98, 81, 38, 195 },
                            PasswordSalt = new byte[] { 54, 42, 28, 151, 37, 146, 91, 51, 52, 216, 65, 141, 157, 16, 63, 164, 10, 213, 32, 82, 168, 168, 188, 117, 63, 68, 166, 138, 134, 83, 201, 176, 84, 14, 185, 154, 48, 61, 170, 219, 139, 95, 44, 158, 40, 51, 18, 152, 163, 166, 46, 43, 59, 7, 207, 128, 153, 115, 233, 192, 103, 151, 41, 169, 170, 237, 79, 230, 77, 3, 27, 44, 161, 98, 177, 202, 107, 104, 127, 29, 103, 164, 248, 5, 2, 84, 249, 231, 218, 218, 144, 213, 104, 228, 30, 32, 21, 68, 54, 55, 74, 150, 197, 44, 70, 255, 45, 249, 115, 154, 83, 177, 34, 34, 122, 191, 2, 101, 171, 106, 92, 158, 236, 162, 225, 6, 210, 241 },
                            Phone = "12355551234",
                            Sex = "男",
                            isSuper = false
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2023, 5, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(1112),
                            Email = "duyou7@example.com",
                            JobId = 9,
                            Name = "萧玉晨",
                            PasswordHash = new byte[] { 193, 126, 114, 212, 29, 138, 149, 19, 191, 218, 90, 30, 54, 169, 57, 56, 14, 24, 98, 131, 129, 250, 145, 44, 135, 115, 117, 239, 24, 180, 208, 105, 36, 4, 135, 49, 124, 227, 161, 42, 151, 15, 48, 6, 17, 76, 169, 194, 228, 180, 34, 39, 100, 244, 128, 239, 195, 162, 7, 14, 98, 81, 38, 195 },
                            PasswordSalt = new byte[] { 54, 42, 28, 151, 37, 146, 91, 51, 52, 216, 65, 141, 157, 16, 63, 164, 10, 213, 32, 82, 168, 168, 188, 117, 63, 68, 166, 138, 134, 83, 201, 176, 84, 14, 185, 154, 48, 61, 170, 219, 139, 95, 44, 158, 40, 51, 18, 152, 163, 166, 46, 43, 59, 7, 207, 128, 153, 115, 233, 192, 103, 151, 41, 169, 170, 237, 79, 230, 77, 3, 27, 44, 161, 98, 177, 202, 107, 104, 127, 29, 103, 164, 248, 5, 2, 84, 249, 231, 218, 218, 144, 213, 104, 228, 30, 32, 21, 68, 54, 55, 74, 150, 197, 44, 70, 255, 45, 249, 115, 154, 83, 177, 34, 34, 122, 191, 2, 101, 171, 106, 92, 158, 236, 162, 225, 6, 210, 241 },
                            Phone = "12355557766",
                            Sex = "女",
                            isSuper = false
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2023, 5, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(1113),
                            Email = "duyou8@example.com",
                            JobId = 7,
                            Name = "丁钧",
                            PasswordHash = new byte[] { 193, 126, 114, 212, 29, 138, 149, 19, 191, 218, 90, 30, 54, 169, 57, 56, 14, 24, 98, 131, 129, 250, 145, 44, 135, 115, 117, 239, 24, 180, 208, 105, 36, 4, 135, 49, 124, 227, 161, 42, 151, 15, 48, 6, 17, 76, 169, 194, 228, 180, 34, 39, 100, 244, 128, 239, 195, 162, 7, 14, 98, 81, 38, 195 },
                            PasswordSalt = new byte[] { 54, 42, 28, 151, 37, 146, 91, 51, 52, 216, 65, 141, 157, 16, 63, 164, 10, 213, 32, 82, 168, 168, 188, 117, 63, 68, 166, 138, 134, 83, 201, 176, 84, 14, 185, 154, 48, 61, 170, 219, 139, 95, 44, 158, 40, 51, 18, 152, 163, 166, 46, 43, 59, 7, 207, 128, 153, 115, 233, 192, 103, 151, 41, 169, 170, 237, 79, 230, 77, 3, 27, 44, 161, 98, 177, 202, 107, 104, 127, 29, 103, 164, 248, 5, 2, 84, 249, 231, 218, 218, 144, 213, 104, 228, 30, 32, 21, 68, 54, 55, 74, 150, 197, 44, 70, 255, 45, 249, 115, 154, 83, 177, 34, 34, 122, 191, 2, 101, 171, 106, 92, 158, 236, 162, 225, 6, 210, 241 },
                            Phone = "12355556866",
                            Sex = "男",
                            isSuper = false
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2023, 5, 21, 19, 40, 3, 488, DateTimeKind.Local).AddTicks(1115),
                            Email = "duyou9@example.com",
                            JobId = 9,
                            Name = "沈琼",
                            PasswordHash = new byte[] { 193, 126, 114, 212, 29, 138, 149, 19, 191, 218, 90, 30, 54, 169, 57, 56, 14, 24, 98, 131, 129, 250, 145, 44, 135, 115, 117, 239, 24, 180, 208, 105, 36, 4, 135, 49, 124, 227, 161, 42, 151, 15, 48, 6, 17, 76, 169, 194, 228, 180, 34, 39, 100, 244, 128, 239, 195, 162, 7, 14, 98, 81, 38, 195 },
                            PasswordSalt = new byte[] { 54, 42, 28, 151, 37, 146, 91, 51, 52, 216, 65, 141, 157, 16, 63, 164, 10, 213, 32, 82, 168, 168, 188, 117, 63, 68, 166, 138, 134, 83, 201, 176, 84, 14, 185, 154, 48, 61, 170, 219, 139, 95, 44, 158, 40, 51, 18, 152, 163, 166, 46, 43, 59, 7, 207, 128, 153, 115, 233, 192, 103, 151, 41, 169, 170, 237, 79, 230, 77, 3, 27, 44, 161, 98, 177, 202, 107, 104, 127, 29, 103, 164, 248, 5, 2, 84, 249, 231, 218, 218, 144, 213, 104, 228, 30, 32, 21, 68, 54, 55, 74, 150, 197, 44, 70, 255, 45, 249, 115, 154, 83, 177, 34, 34, 122, 191, 2, 101, 171, 106, 92, 158, 236, 162, 225, 6, 210, 241 },
                            Phone = "12355556699",
                            Sex = "女",
                            isSuper = false
                        });
                });

            modelBuilder.Entity("SkillSystem.Shared.Course", b =>
                {
                    b.HasOne("SkillSystem.Shared.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSystem.Shared.SkillType", "SkillType")
                        .WithMany()
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("SkillType");
                });

            modelBuilder.Entity("SkillSystem.Shared.Job", b =>
                {
                    b.HasOne("SkillSystem.Shared.Department", "Department")
                        .WithMany("JobList")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SkillSystem.Shared.SkillVariant", b =>
                {
                    b.HasOne("SkillSystem.Shared.Skill", "Skill")
                        .WithMany("Variants")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSystem.Shared.SkillType", "SkillType")
                        .WithMany()
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("SkillType");
                });

            modelBuilder.Entity("SkillSystem.Shared.Training", b =>
                {
                    b.HasOne("SkillSystem.Shared.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SkillSystem.Shared.TrainingItem", b =>
                {
                    b.HasOne("SkillSystem.Shared.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSystem.Shared.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillSystem.Shared.User", b =>
                {
                    b.HasOne("SkillSystem.Shared.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SkillSystem.Shared.Department", b =>
                {
                    b.Navigation("JobList");
                });

            modelBuilder.Entity("SkillSystem.Shared.Skill", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
